### ISSUE TITLE
A Server, on retrieving message from a client, broadcasts it to its servers list

### ISSUE THREAD

**Issue by progala2** [progala2/SecretForum#33]
Here we only pushing forward the messages received from others to the servers list.

**Comment by matyjasiakm** [comment]
The server will check from time to time whether there are any new messages on the given servers, if so they download them.

**Comment by matyjasiakm** [comment]
Client can push messages directly to servers on list.

**Comment by progala2** [comment]
> The server will check from time to time whether there are any new messages on the given servers, if so they download them.

It is not in this issue: It will be a separate task 😄 
In this only pushing forward the messages received from others.

**Comment by progala2** [comment]
> > The server will check from time to time whether there are any new messages on the given servers, if so they download them.
> 
> It is not in this issue: It will be a separate task 😄
> In this only pushing forward the messages received from others.

#34 <- here is the second issue/task

**Comment by matyjasiakm** [comment]
Ok, I only note that.

**Comment by progala2** [comment]
Client pushes a message to the server and server propagate it to others when the message is new, i.e. the message at arrival is checked if it already exists if not - propagate
