### ISSUE TITLE
Server class shouldn't be in the Infrastructure layer.

### ISSUE THREAD

**Issue by progala2** [progala2/SecretForum#42]
I haven't noticed it in #15 but there is a misunderstanding in the architecture layers.
The server shouldn't be in the infrastructure layer that's why there is a problem how the server can invokes queries and commands if these two are in Application Layers.
Therefore the Server class should be moved to the presentation layer and then the server can use all the queries and commands from the application layer.

**Expected Result**
- Client as it is in Infrastructure.P2P project; no changes here.
- Server should be a separate project similar to the console project (so you can run it in separate instance). Maybe the ServerLogger project can be used for that.
- ConsoleApp instead of using commands like ServerStart/ServerStop etc. should reference to the new ServerConsole project and run/stops it from there. 
- Server and Client share some similar classes/enums (like the ServerMessageId enum). If that's the case another project can be created, called: "SecretForum.Communication" and the shared things will be put here.

The change is simple just move the classes around to different projects 😄

**Comment by matyjasiakm** [comment]
1. The server should be something like a ConsoleApp displaying only logs?  
2. Should the server class be in the presentation layer? 
3. ConsoleApp should start new process with server.exe ?

**Comment by progala2** [comment]
> 1. The server should be something like a ConsoleApp displaying only logs?
> 2. Should the server class be in the presentation layer?
> 3. ConsoleApp should start new process with server.exe ?
> 4. Path to Db and List of servers etc. should be in server config file?

1. Yes.
2. Yes, in some project in this layer
3. No, you can just reference the project in the ConsoleApp and just do metaphorically "new Server(..)" but if it is easier this way i won't be sad.
4. Maybe we can put the Server class to the ConsoleApp project? In Folder Server and then the 1st, 2nd, 3rd question will be solved (you will be able to run and stop it from the console).
What do you think?

**Comment by matyjasiakm** [comment]
![image](https://user-images.githubusercontent.com/47790324/69762206-d621d080-1169-11ea-9fa6-cee784e7cc11.png)

**Comment by progala2** [comment]
It will be very easy to do and shouldn't break any rules regarding the architecture 🤓

**Comment by matyjasiakm** [comment]
And add server to servicecollection?

**Comment by matyjasiakm** [comment]
Or in serviceApp like Mediator and ConsoleConfig?

**Comment by progala2** [comment]
in serviceApp

**Comment by progala2** [comment]
It depends how you will start it and stop it but keeping it as a singleton should do the work, I suppose.
